import axios from 'axios'
import {IProjectExpMulModel} from '../../../models/master-page/IProjectExpenseModel'
const BASE_API_URL = process.env.REACT_APP_API_URL
// =================Kyc Document URL=====================
export const GET_PROJECT_EXPENSE_LIST = `${BASE_API_URL}/ProjectExpense/GetProjectExpenseWebList`
export const ADD_PROJECT_EXPENSE_DETAILS = `${BASE_API_URL}/ProjectExpense/AddProjectExpenseDetails`
export const ADD_MULTIPLE_PROJECT_EXPENSE_DETAILS = `${BASE_API_URL}/ProjectExpense/AddMultipleProjectExpenseDetails`
export const UPDATE_PROJECT_EXPENSE_DETAILS = `${BASE_API_URL}/ProjectExpense/UpdateProjectExpenseDetails`
export const GET_PROJECT_EXPENSE_BY_PROJECT_EXPENSE_ID = `${BASE_API_URL}/ProjectExpense/GetProjectExpenseDataByProjectExpenseID`
export const DELETE_PROJECT_EXPENSE = `${BASE_API_URL}/ProjectExpense/DeleteProjectExpense`
export function getProjectExpenseList() {
  return axios.get(GET_PROJECT_EXPENSE_LIST)
}
export function addProjectExpense(
  projectID: number,
  title: string,
  expenseDate: string,
  documentPath: string,
  amount: number,
  createBy: number,
  ipAddress: string,
  cashAccountID: number,
  transactionModeID: number,
  transactionID: string,
  chequeBankName: string,
  chequeBankBranch: string,
  chequeDate: string,
  chequeAmount: number,
  chequeNumber: string,
  cashAccountBankID: number,
  vendorInvoiceNo: string,
  employeeID: number,
  isgst: boolean,
  gstTypeID: number,
  cgstVal: number,
  sgstVal: number,
  igstVal: number,
  gstAmount: number,
  sgstPer: number,
  cgstPer: number,
  igstPer: number,
  isTdsDeduct: boolean,
  tdsPer: number,
  tdsAmount: number,
  afterTDSAmt: number,
  afterGSTAmount: number,
  finalAmount: number,
  description: string
) {
  return axios.post(ADD_PROJECT_EXPENSE_DETAILS, {
    projectID,
    title,
    expenseDate,
    documentPath,
    amount,
    createBy,
    ipAddress,
    cashAccountID,
    transactionModeID,
    transactionID,
    chequeBankName,
    chequeBankBranch,
    chequeDate,
    chequeAmount,
    chequeNumber,
    cashAccountBankID,
    vendorInvoiceNo,
    employeeID,
    isgst,
    gstTypeID,
    cgstVal,
    sgstVal,
    igstVal,
    gstAmount,
    sgstPer,
    cgstPer,
    igstPer,
    isTdsDeduct,
    tdsPer,
    tdsAmount,
    afterTDSAmt,
    afterGSTAmount,
    finalAmount,
    description,
  })
}

export function updateProjectExpense(
  projectExpenseID: number,
  projectID: number,
  title: string,
  expenseDate: string,
  documentPath: string,
  amount: number,
  updateBy: number,
  ipAddress: string,
  cashAccountID: number,
  transactionModeID: number,
  transactionID: string,
  chequeBankName: string,
  chequeBankBranch: string,
  chequeDate: string,
  chequeAmount: number,
  chequeNumber: string,
  cashAccountBankID: number,
  vendorInvoiceNo: string,
  employeeID: number,
  isgst: boolean,
  gstTypeID: number,
  cgstVal: number,
  sgstVal: number,
  igstVal: number,
  gstAmount: number,
  sgstPer: number,
  cgstPer: number,
  igstPer: number,
  isTdsDeduct: boolean,
  tdsPer: number,
  tdsAmount: number,
  afterTDSAmt: number,
  afterGSTAmount: number,
  finalAmount: number,
  description: string
) {
  return axios.post(UPDATE_PROJECT_EXPENSE_DETAILS, {
    projectExpenseID,
    projectID,
    title,
    expenseDate,
    documentPath,
    amount,
    updateBy,
    ipAddress,
    cashAccountID,
    transactionModeID,
    transactionID,
    chequeBankName,
    chequeBankBranch,
    chequeDate,
    chequeAmount,
    chequeNumber,
    cashAccountBankID,
    vendorInvoiceNo,
    employeeID,
    isgst,
    gstTypeID,
    cgstVal,
    sgstVal,
    igstVal,
    gstAmount,
    sgstPer,
    cgstPer,
    igstPer,
    isTdsDeduct,
    tdsPer,
    tdsAmount,
    afterTDSAmt,
    afterGSTAmount,
    finalAmount,
    description,
  })
}
export function getProjectExpenseByProjectExpenseId(projectExpenseID: number) {
  return axios.post(GET_PROJECT_EXPENSE_BY_PROJECT_EXPENSE_ID, {projectExpenseID})
}

export function deleteProjectExpenseData(projectExpenseID: number) {
  return axios.post(DELETE_PROJECT_EXPENSE, {projectExpenseID})
}

export function addMultipleProjectExpenseAPI(
  projectList: IProjectExpMulModel[],
  title: string,
  expenseDate: string,
  documentPath: string,
  cashAccountID: number,
  transactionModeID: number,
  transactionID: string,
  chequeBankName: string,
  chequeBankBranch: string,
  chequeDate: string,
  chequeAmount: number,
  chequeNumber: string,
  cashAccountBankID: number,
  vendorInvoiceNo: string,
  employeeID: number,
  description: string,
  isgst: boolean,
  gstTypeID: number,
  cgstVal: number,
  sgstVal: number,
  igstVal: number,
  gstAmount: number,
  sgstPer: number,
  cgstPer: number,
  igstPer: number,
  isTdsDeduct: boolean,
  tdsPer: number,
  tdsAmount: number,
  afterTDSAmt: number,
  afterGSTAmount: number,
  finalAmount: number,
  createBy: number,
  ipAddress: string
) {
  return axios.post(ADD_MULTIPLE_PROJECT_EXPENSE_DETAILS, {
    projectList,
    title,
    expenseDate,
    documentPath,
    cashAccountID,
    transactionModeID,
    transactionID,
    chequeBankName,
    chequeBankBranch,
    chequeDate,
    chequeAmount,
    chequeNumber,
    cashAccountBankID,
    vendorInvoiceNo,
    employeeID,
    description,
    isgst,
    gstTypeID,
    cgstVal,
    sgstVal,
    igstVal,
    gstAmount,
    sgstPer,
    cgstPer,
    igstPer,
    isTdsDeduct,
    tdsPer,
    tdsAmount,
    afterTDSAmt,
    afterGSTAmount,
    finalAmount,
    createBy,
    ipAddress,
  })
}
